# -*- coding: utf-8 -*-
"""student_performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoqM7sL0Be_lWsgJ9NNAFhXTescgwBFn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/StudentsPerformance.csv")
df

df.head()

df.tail()

df.shape

df.info()

df.describe()

print(df.isnull().sum())

df = df.dropna()

score_columns = ['math score', 'reading score', 'writing score']
score_columns

df[score_columns].describe()

df[score_columns].mean()

df[score_columns].median()

df[score_columns].mode()

df[score_columns].std()

df[score_columns].quantile(0.25)

df[score_columns].quantile(0.50)

df[score_columns].quantile(0.75)

df['Total Score'] = df['math score'] + df['reading score'] + df['writing score']
df

df['Percentage'] = (df['Total Score'] / (300)) * 100
df

df[['Total Score', 'Percentage']].head()